### PR TITLE
Simplify manager initialization

### PR DESCRIPTION
**Pull request by utkuufuk**
The aim of this particular PR is to simplify the initialization of `Manager`. 

Simplifying the `NewManager` function will enable us to easily test `manager.go` in the future, because it can now be initialized with fake data.

Once this gets merged, the next goal should be to extract more files from `manager.go`, similar to how `database.go` has been extracted by this PR.

### CODE REVIEW

**Comment by paddlesteamer** [comment]
I like all the simplifications. I did some changes because it was broken. I added SetPath:
https://github.com/paddlesteamer/hdn-drv/blob/daa91ba87b6d30409fa1c96c305d8c8cc8dd2236/internal/sqlite/client.go#L59-L61

I don't like the way we initialize or import database now - like calling SetPath externally when we have already had DB in remote storage but calling it internally when we initialize it with `InitDB`. Too asymmetric for me :D And also not simple. Maybe we can go back to creating a `getDBConnection` function in manager and provide db path `sqlite.NewClient` everytime. This would be useful if we change the database file path in runtime for some reason - only database file path reference would be the `database` struct:
https://github.com/paddlesteamer/hdn-drv/blob/daa91ba87b6d30409fa1c96c305d8c8cc8dd2236/internal/manager/database.go#L10-L16

Still, I'm merging this, we can change it later.

**Comment by paddlesteamer** [comment]
I really like the changes, by the way, I wanted to mention it again :1st_place_medal:

**Comment by utkuufuk** [comment]
> I don't like the way we initialize or import database now

@paddlesteamer I also found it confusing and honestly didn't understand the logic 100%, so this was the best I was able to come up with.

I think it would **not** be overkill to put all the DB setup/import logic in a dedicated file, and break things up into even smaller functions in it. Then we can just call something like `initDB()` from `main`. Because `main` is a bit crowded ATM with all that logic.

**Comment by paddlesteamer** [comment]
Ok, first I will implement OAuth flow and then we can go over it once all elements of the code are in place.

**Pull request merged**
